### PR TITLE
Including CodeOwners and Maintainers

### LINKED ISSUE #1: Update CODEOWNERS file with initial code owners

### PR DESCRIPTION
**Pull request by jgarciahospital**
#### What type of PR is this?

* subproject management

#### What this PR does / why we need it:

Include repository codeowners and maintainers

#### Which issue(s) this PR fixes:

Fixes #1 #2

### CODE REVIEW

**Comment by jgarciahospital** [comment]
@rartych @ KevScarr it would be better to keep 2 codeowners from different companis, in case any of you want to also take the role.

**Comment by hdamker** [comment]
@jgarciahospital updated the GitHub Teams, waiting for @KevScarr and @amg77 to accept the invitation to CAMARA org.
And waiting for updates from @rartych and/or @KevScarr about the question above regarding Codeowner.

**Comment by KevScarr** [comment]
@hdamker Confirmed from Vodafone it will be myself so happy to support being a Codeowner

**Review by KevScarr — APPROVED** [review]
Confirming kevscarr will lead from Vodafone.

**Comment by hdamker** [comment]
We are good to go here. @camaraproject/customer-insights_codeowners and @camaraproject/customer-insights_maintainers are updated, in addition I have added all maintainers to the mailing list.

**Review by hdamker — APPROVED** [review]

**Pull request merged**
